module.exports = {
  output: {
    LEVELS: [
      'standard',
      'error',
      'buffer',
    ],
    standard: (...args) => process.emit('output', 'standard', ...args),
    error: (...args) => process.emit('output', 'error', ...args),
    buffer: (...args) => process.emit('output', 'buffer', ...args),
  },
  log: {
    LEVELS: [
      'notice',
      'error',
      'warn',
      'info',
      'verbose',
      'http',
      'silly',
      'timing',
      'pause',
      'resume',
    ],
    error: (...args) => process.emit('log', 'error', ...args),
    notice: (...args) => process.emit('log', 'notice', ...args),
    warn: (...args) => process.emit('log', 'warn', ...args),
    info: (...args) => process.emit('log', 'info', ...args),
    verbose: (...args) => process.emit('log', 'verbose', ...args),
    http: (...args) => process.emit('log', 'http', ...args),
    silly: (...args) => process.emit('log', 'silly', ...args),
    timing: (...args) => process.emit('log', 'timing', ...args),
    pause: (...args) => process.emit('log', 'pause', ...args),
    resume: (...args) => process.emit('log', 'resume', ...args),
  },
}
